data:
  csv_file: /content/train.csv
  img_dir: /content/images
  label_dir: /content/labels
  test_file: /content/test.csv
split_size: 7
number_boxes: 2
number_classes: 20
train_batch: 32
dev_batch: 32
test_batch: 32
num_epochs: 100
patience: 5
learning_rate: 0.00005
save_path: checkpoint